import { baseURl, sleep } from "@/lib/utils";
import { Metadata } from "next/types";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	openGraph: {
		type: "website",
		locale: "en_US",
		url: "https://nextjs.org",
		siteName: "Next.js",
		title: "Create Next App",
		description: "Generated by create next app",
		images: [
			{
				url: `${baseURl}/opengraph/suspense`,
				width: 1200,
				height: 630,
				alt: "Next.js Blog Example with **MDX**",
			},
		],
	},
};

export default async function Page() {
	await sleep(2000);
	const data = await fetch(new URL(`${baseURl}/api`));
	const json = await data.json();

	return (
		<div>
			<h1>Page</h1>
			<p>{json.message}</p>
		</div>
	);
}
